### ISSUE TITLE
Error: cannot reach http://json-schema.org/schema

### ISSUE THREAD

**Issue by briviere** [tacoss/raml-mockup#10]
Any idea why I would be getting this error?

raml-mockup api.raml
Error: cannot reach http://json-schema.org/song-schema.json

running version 0.1.7 raml-mockup

thanks

Brian

**Comment by pateketrueke** [comment]
Are you trying to run the given example within the repository?

I guess you forgot the `--directory` and `--fakeroot` options, please checkout the README.

The fact is you'll need to provide a directory where your local schemas exists, and you must provide a valid fakeroot in order to recognize those external references.

If not, raml-mockup will try to download any remote schemas if they're not being faked locally.

**Comment by briviere** [comment]
Okay for some reason I thought I had it working without specifying the --fakeroot and --directory.

thanks

Brian
